/**
 * @file stepper.h
 * @brief Non-blocking stepper motor driver — step scheduling and velocity control.
 *
 * Design constraints:
 *  - No delay() or delayMicroseconds() anywhere in this module (FR-026).
 *  - Velocity updates must NOT interrupt an axis mid-flight; nextStepTime and
 *    stepCount are preserved across velocity changes (FR-013).
 *  - Step pulse is generated by two back-to-back digitalWrite() calls with no
 *    inserted delay. AVR GPIO toggle latency (~125 ns/instruction) satisfies the
 *    A4988/DRV8825 minimum 1 µs STEP pulse width requirement.
 *  - stepCount is int32_t; overflow guard clamps it to INT32_MAX / INT32_MIN
 *    before wrap-around (FR-022).
 */

#pragma once

#include <stdint.h>

// ─────────────────────────────────────────────────────────────────────────────
// Data model
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Per-axis mutable state for one stepper motor.
 *
 * Members intentionally use standard C++ types (uint8_t, unsigned long) so the
 * struct can be compiled by host GCC for native unit tests without Arduino.h.
 */
struct StepperAxis {
    uint8_t       stepPin;           ///< Arduino digital pin number for STEP signal
    uint8_t       dirPin;            ///< Arduino digital pin number for DIR signal
    float         velocity;          ///< Current velocity in caller-defined speed units (negative = reverse)
    unsigned long stepIntervalUs;    ///< Time between steps in microseconds (derived from velocity)
    unsigned long nextStepTimeUs;    ///< micros() timestamp of the next scheduled step
    int32_t       stepCount;         ///< Cumulative signed step count (positive = forward)
};

// ─────────────────────────────────────────────────────────────────────────────
// API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Initialise a StepperAxis struct.
 *
 * Configures pinModes, zeros velocity and step counters, and sets nextStepTimeUs
 * to the current micros() so the axis is ready to step immediately if commanded.
 *
 * @param[out] axis     Axis struct to initialise.
 * @param[in]  stepPin  Arduino digital pin for STEP signal.
 * @param[in]  dirPin   Arduino digital pin for DIR signal.
 */
void stepperInit(StepperAxis& axis, uint8_t stepPin, uint8_t dirPin);

/**
 * @brief Set the desired velocity for an axis.
 *
 * Velocity of 0 stops the axis.  The magnitude is clamped so that the resulting
 * step interval never falls below MIN_STEP_INTERVAL_US (FR-014).
 *
 * IMPORTANT: this function preserves nextStepTimeUs and stepCount — it does NOT
 * reset or pause the scheduling state (FR-013).
 *
 * @param[in,out] axis      Target axis.
 * @param[in]     velocity  Desired velocity in speed units.
 *                          Positive = forward (high DIR), negative = reverse (low DIR).
 */
void stepperSetVelocity(StepperAxis& axis, float velocity);

/**
 * @brief Service one axis; emit a step pulse if scheduled time has elapsed.
 *
 * Must be called every loop() iteration with no blocking delays elsewhere.
 * Emits at most one step pulse per call.
 *
 * Overflow guard: if stepCount would overflow int32_t, it is clamped to
 * INT32_MAX or INT32_MIN instead of wrapping (FR-022).
 *
 * @param[in,out] axis  Axis to service.
 */
void stepperTick(StepperAxis& axis);
